#!/usr/bin/env bash

set -e

# in case we're running root from 'sudo bash' or similar and $HOME isn't updated
if [ "$USER" == "root" ]; then
  export HOME=/root
fi

# Check if running in Google Colab environment
if [ ! -z "$COLAB_JUPYTER_IP" ]; then
    if ! command -v zsh &> /dev/null; then
        echo "zsh is not installed. Installing zsh..."
        sudo apt update && sudo apt install zsh -y
    fi
fi


CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
