#!/usr/bin/env Rscript

# don't show warnings...
# this is to silenze a warning about the input mode,
# this is probably not the best way to do that...
options(warn = -1)

con <- file("stdin")
load(con)

# dd is the dataframe holding rdat-deconstructed data frame input

noop <- function(input) {}

if(is.data.frame(dd)) {
  tryCatch(
   write.table(dd, "",  sep = "\t", col.names = TRUE, row.names = FALSE, quote = FALSE),
   warning = noop, error = noop)
} else if(is.vector(dd)) {
  cat(paste(dd, collapse = "\n"))
  cat("\n")
} else {
  print("Sorry, can only tadr from dataframe and vector input for now")
}
